### ISSUE TITLE
Enhance create project error message

### ISSUE THREAD

**Issue by surrealist** [surrealist/dev-dynamo#3]
For the project create API endpoint
```
POST /api/v1/projects
```

When the template name is not found, list all available template names in the error message.

Sample response error message:
```
Template 'Snowing' is not found. All available templates are Sunny, Rainy, and Darky.
```

**Comment by armshare** [comment]
[Pull Request] (https://github.com/surrealist/dev-dynamo/pull/12) นี้ครับผม
